// <auto-generated />
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Intervals")]
[assembly: AssemblyDescription("A library for working with intervals and sets.  Includes a generic interface so that intervals of any type may be created.")]
[assembly: AssemblyCompany("John Gietzen")]
[assembly: AssemblyProduct("Intervals")]
[assembly: AssemblyCopyright("Copyright © 2016 John Gietzen")]

[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

[assembly: Guid("d9ed14de-bf00-4e32-b09d-9cdc6c3cd462")]
