// <auto-generated />
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Intervals")]
[assembly: AssemblyDescription("A library for working with intervals and sets.  Includes a generic interface so that intervals of any type may be created.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("John Gietzen")]
[assembly: AssemblyProduct("Intervals")]
[assembly: AssemblyCopyright("Copyright © 2012 John Gietzen")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

[assembly: Guid("d9ed14de-bf00-4e32-b09d-9cdc6c3cd462")]

[assembly: AssemblyVersion("1.2.*")]
[assembly: AssemblyFileVersion("1.2.0.0")]
