// <auto-generated />
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Intervals.Tests")]
[assembly: AssemblyProduct("Intervals")]
[assembly: AssemblyCopyright("Copyright © 2012 John Gietzen")]

[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

[assembly: Guid("d9ed14de-bf00-4e32-b09d-9cdc6c3cd462")]
